apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-app
  labels:
    app: calendar-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar-app
  template:
    metadata:
      labels:
        app: calendar-app
    spec:
      containers:
        - name: calendar-app
          image: ghcr.io/sayjeyhi/calendar-app:latest
          ports:
            - containerPort: 8080

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
          resources:
            limits:
              cpu: '1000m'
              memory: '1024Mi'
            requests:
              cpu: '500m'
              memory: '500Mi'
